// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConversationSubscriptionController from "./conversation_subscription_controller"
application.register("conversation-subscription", ConversationSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import ProfilesController from "./profiles_controller"
application.register("profiles", ProfilesController)

import UserGamesController from "./user_games_controller"
application.register("user-games", UserGamesController)
